import 'package:flutter/material.dart';

import '../../../core/widgets/primary_button.dart';
import '../../../data/models/app_enums.dart';
import '../../../data/models/driver_vehicle.dart';
import '../../../data/repositories/driver_vehicle_repository.dart';
import '../../shared/widgets/feature_templates.dart';

class AddVehicleScreen extends StatefulWidget {
  const AddVehicleScreen({super.key});

  @override
  State<AddVehicleScreen> createState() => _AddVehicleScreenState();
}

class _AddVehicleScreenState extends State<AddVehicleScreen> {
  final _repository = DriverVehicleRepository();
  final _modelController = TextEditingController();
  final _plateNumberController = TextEditingController();
  String _type = 'Classic';
  String _plateType = 'Private';
  String _color = 'Black';
  int _seats = 4;
  bool _isSaving = false;

  @override
  void dispose() {
    _modelController.dispose();
    _plateNumberController.dispose();
    super.dispose();
  }

  Future<void> _saveVehicle() async {
    final model = _modelController.text.trim();
    final plateNumber = _plateNumberController.text.trim();

    if (model.isEmpty || plateNumber.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please fill in all required fields.')),
      );
      return;
    }

    setState(() => _isSaving = true);

    try {
      final vehicle = DriverVehicle(
        id: '', // Generated by Firestore
        driverId: '', // Set by repository
        type: _type,
        model: model,
        plateNumber: plateNumber.toUpperCase(),
        plateType: _plateType,
        color: _color,
        seats: _seats,
        isDefault: false,
        documentStatus: DocumentStatus.pending,
      );

      await _repository.addVehicle(vehicle);
      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Vehicle submitted for approval.')),
      );
      Navigator.pop(context, true);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('We could not save this vehicle. Please try again.'),
        ),
      );
    } finally {
      if (mounted) {
        setState(() => _isSaving = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) => FeatureScaffold(
    title: 'Add New Vehicle',
    children: [
      DropdownButtonFormField<String>(
        initialValue: _type,
        decoration: const InputDecoration(labelText: 'Vehicle Type'),
        items: const ['Classic', 'VIP', 'XL', 'Delivery']
            .map((value) => DropdownMenuItem(value: value, child: Text(value)))
            .toList(),
        onChanged: (val) {
          if (val != null) setState(() => _type = val);
        },
      ),
      const SizedBox(height: 14),
      TextField(
        controller: _modelController,
        decoration: const InputDecoration(
          labelText: 'Vehicle Model',
          hintText: 'e.g. Toyota Camry 2020',
        ),
      ),
      const SizedBox(height: 14),
      TextField(
        controller: _plateNumberController,
        decoration: const InputDecoration(
          labelText: 'Plate Number',
          hintText: 'ABC 123 CD',
        ),
      ),
      const SizedBox(height: 14),
      DropdownButtonFormField<String>(
        initialValue: _plateType,
        decoration: const InputDecoration(labelText: 'Plate Type'),
        items: const ['Private', 'Commercial']
            .map((value) => DropdownMenuItem(value: value, child: Text(value)))
            .toList(),
        onChanged: (val) {
          if (val != null) setState(() => _plateType = val);
        },
      ),
      const SizedBox(height: 14),
      DropdownButtonFormField<String>(
        initialValue: _color,
        decoration: const InputDecoration(labelText: 'Color'),
        items: const ['Black', 'White', 'Silver', 'Blue', 'Red']
            .map((value) => DropdownMenuItem(value: value, child: Text(value)))
            .toList(),
        onChanged: (val) {
          if (val != null) setState(() => _color = val);
        },
      ),
      const SizedBox(height: 14),
      DropdownButtonFormField<int>(
        initialValue: _seats,
        decoration: const InputDecoration(labelText: 'Seats'),
        items: const [2, 4, 5, 7]
            .map(
              (value) =>
                  DropdownMenuItem(value: value, child: Text('$value seats')),
            )
            .toList(),
        onChanged: (val) {
          if (val != null) setState(() => _seats = val);
        },
      ),
      const SizedBox(height: 22),
      PrimaryButton(
        label: 'Save Vehicle',
        isLoading: _isSaving,
        onPressed: _isSaving ? null : _saveVehicle,
      ),
    ],
  );
}
